/* tslint:disable */
/* eslint-disable */
/**
 * users API
 * API for managing data in the users database
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiProfile
 */
export interface ApiProfile {
    /**
     * (Unique value required) (Primary key)
     * @type {string}
     * @memberof ApiProfile
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProfile
     */
    'name': string;
}

