/* tslint:disable */
/* eslint-disable */
/**
 * users API
 * API for managing data in the users database
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiProfileListColumnsInner
 */
export interface ApiProfileListColumnsInner {
    /**
     * Column name
     * @type {string}
     * @memberof ApiProfileListColumnsInner
     */
    'name': string;
    /**
     * Data type of the column
     * @type {string}
     * @memberof ApiProfileListColumnsInner
     */
    'dataType': ApiProfileListColumnsInnerDataTypeEnum;
    /**
     * Whether the column allows null values
     * @type {boolean}
     * @memberof ApiProfileListColumnsInner
     */
    'nullable': boolean;
}

export const ApiProfileListColumnsInnerDataTypeEnum = {
    Text: 'TEXT',
    Integer: 'INTEGER',
    Bigint: 'BIGINT',
    Decimal: 'DECIMAL',
    Boolean: 'BOOLEAN',
    Date: 'DATE',
    Timestamp: 'TIMESTAMP',
    Json: 'JSON'
} as const;

export type ApiProfileListColumnsInnerDataTypeEnum = typeof ApiProfileListColumnsInnerDataTypeEnum[keyof typeof ApiProfileListColumnsInnerDataTypeEnum];


