/* tslint:disable */
/* eslint-disable */
/**
 * users API
 * API for managing data in the users database
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiProfileListColumnsInner } from './api-profile-list-columns-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiProfileListPagination } from './api-profile-list-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiProfileListRowsInner } from './api-profile-list-rows-inner';

/**
 * Paginated list of profile records
 * @export
 * @interface ApiProfileList
 */
export interface ApiProfileList {
    /**
     * Metadata about table columns
     * @type {Array<ApiProfileListColumnsInner>}
     * @memberof ApiProfileList
     */
    'columns': Array<ApiProfileListColumnsInner>;
    /**
     * List of records
     * @type {Array<ApiProfileListRowsInner>}
     * @memberof ApiProfileList
     */
    'rows': Array<ApiProfileListRowsInner>;
    /**
     * 
     * @type {ApiProfileListPagination}
     * @memberof ApiProfileList
     */
    'pagination': ApiProfileListPagination;
}

